### DISCUSSION TITLE
LR Multicast Not Functioning As Expected (ZVIDAR  Z-CM-V01)

### DISCUSSION THREAD

**Discussion by alexschneider** [zwave-js/zwave-js#7015] [Request Support / Investigate Issue] [answered]
### Checklist

- [X] I have read and followed the above instructions
- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there or the fix **did not work**.

### Describe the issue

What is happening?
When sending a multicast command to raise/lower my shades they don't all raise or lower simultaneously.

What did you expect to happen instead?
All the shades raise/lower simultaneously

Send a multicast driver command commanding shades to raise/lower (I did so via homeassistant as shown):
```
service: zwave_js.multicast_set_value
metadata: {}
data:
  command_class: "38"
  endpoint: "0"
  property: Down
  value: true
target:
  entity_id: >-
    {{ expand(state_attr('light.shades',
    'entity_id'))|map(attribute='entity_id')|list }}
```

Anything else we should know?

### Software versions

Z-Wave JS UI:
zwave-js-ui: 9.14.6
zwave-js: 12.12.4
home id: 3806735750
home hex: 0xe2e62d86

### Device information

I don't think it's device related but here's the info:

Manufacturer: ZVIDAR
Model name:  Z-CM-V01 
Node ID: 256-265

### Checklist

- [X] I [made sure](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index?id=rule-1-use-the-driver-log-luke) to provide a **driver log** on level **debug**.

- [ ] The log includes a re-interview of the problematic device _(if applicable)_.

- [ ] The log includes the problematic interaction with the device _(if applicable)_.

- [X] I provided the node ID of the problematic device _(if applicable)_.

### Upload Logfile

[z-ui_current.log](https://github.com/user-attachments/files/16239973/z-ui_current.log)

[a comment by an automated account is not shown]
