### DISCUSSION TITLE
Device not responding to multicast

### DISCUSSION THREAD

**Discussion by alexschneider** [zwave-js/zwave-js#7027] [Request Support / Investigate Issue]
### Checklist

- [X] I have read and followed the above instructions
- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there or the fix **did not work**.

### Describe the issue

What is happening?
When I send a multicast command to all the shades in my house, one consistently doesn't respond. It responds fine when I send a direct command though. 

What did you expect to happen instead?
The node responds to the command

 Send a multicast driver command commanding shades to raise/lower (I did so via homeassistant as shown):
```
service: zwave_js.multicast_set_value
metadata: {}
data:
  command_class: "38"
  endpoint: "0"
  property: Down
  value: true
target:
  entity_id: >-
    {{ expand(state_attr('light.shades',
    'entity_id'))|map(attribute='entity_id')|list }}
```

Anything else we should know?

### Software versions

zwave-js-ui: 9.16.0
zwave-js: 13.0.0
home id: 3806735750
home hex: 0xe2e62d86

### Device information

Manufacturer: ZVIDAR
Model name: Z-CM-V01
Node ID: 263 (256-265 are all the same device/manufacturer and 263 is the only one not working)

### Checklist

- [X] I [made sure](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index?id=rule-1-use-the-driver-log-luke) to provide a **driver log** on level **debug**.

- [X] The log includes a re-interview of the problematic device _(if applicable)_.

- [X] The log includes the problematic interaction with the device _(if applicable)_.

- [X] I provided the node ID of the problematic device _(if applicable)_.

### Upload Logfile

[zwavejs_current.log](https://github.com/user-attachments/files/16287092/zwavejs_current.log)
